name: Fetch API and Save JSON

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

on:
  schedule:
    - cron: '0 */5 * * *' # run a job every 5 hours
  push:
    branches: [ main ]
env:
  # Setting an environment variable with the value of a configuration variable
  ENDPOINT_HARGA_PANGAN_JAWA_TIMUR: ${{ secrets.ENDPOINT_HARGA_PANGAN_JAWA_TIMUR }}    
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |    
          export YESTERDAY_DATE=$(TZ='Asia/Jakarta' date +"%Y-%m-%d" --date="yesterday")
          export TODAY_DATE=$(TZ='Asia/Jakarta' date +"%Y-%m-%d")

          mkdir -p harga-pangan-jawa-timur
          
          curl -s "${ENDPOINT_HARGA_PANGAN_JAWA_TIMUR}&task=getDailyAvgPrice&tanggal=${YESTERDAY_DATE}" > "harga-pangan-jawa-timur/&task=getDailyAvgPrice&tanggal=${YESTERDAY_DATE}.json"
          curl -s "${ENDPOINT_HARGA_PANGAN_JAWA_TIMUR}&task=getDailyAvgPrice&tanggal=${TODAY_DATE}" > "harga-pangan-jawa-timur/&task=getDailyAvgPrice&tanggal=${TODAY_DATE}.json"

          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "feat: generated by github action"
            git push
          fi
